/** Public STU report IDs. Wire layouts are independently implemented; see docs/protocol-evidence.md. */
export const ReportId = {
  PenData: 0x01,
  Status: 0x03,
  Reset: 0x04,
  HidInformation: 0x06,
  Information: 0x08,
  Capability: 0x09,
  Uid: 0x0a,
  Uid2: 0x0b,
  DefaultMode: 0x0c,
  ReportRate: 0x0d,
  RenderingMode: 0x0e,
  Eserial: 0x0f,
  PenDataEncrypted: 0x10,
  HostPublicKey: 0x13,
  DevicePublicKey: 0x14,
  StartCapture: 0x15,
  EndCapture: 0x16,
  DHprime: 0x1a,
  DHbase: 0x1b,
  ClearScreen: 0x20,
  InkingMode: 0x21,
  InkThreshold: 0x22,
  ClearScreenArea: 0x23,
  StartImageDataArea: 0x24,
  StartImageData: 0x25,
  ImageDataBlock: 0x26,
  EndImageData: 0x27,
  HandwritingThicknessColor: 0x28,
  BackgroundColor: 0x29,
  HandwritingDisplayArea: 0x2a,
  BacklightBrightness: 0x2b,
  ScreenContrast: 0x2c,
  HandwritingThicknessColor24: 0x2d,
  BackgroundColor24: 0x2e,
  BootScreen: 0x2f,
  PenDataOption: 0x30,
  PenDataEncryptedOption: 0x31,
  PenDataOptionMode: 0x32,
  PenDataTimeCountSequenceEncrypted: 0x33,
  PenDataTimeCountSequence: 0x34,
  EncryptionCommand: 0x40,
  EncryptionStatus: 0x50,
  GetReport: 0x80,
  SetResult: 0x81,
  PinPadData: 0x90,
  PinPadDataEncrypted: 0x91,
  PinOperationMode: 0x92,
  OperationMode: 0x93,
  RomStartImageData: 0x94,
  RomImageOccupancy: 0x95,
  RomImageHash: 0x96,
  RomImageDelete: 0x97,
  CurrentImageArea: 0x98,
  EventData: 0x99,
  EventDataEncrypted: 0x9a,
  RomImageDisplay: 0x9b,
  ReportSizeCollection: 0xff,
} as const;
export type ReportId = (typeof ReportId)[keyof typeof ReportId];

export interface ReportDefinition {
  readonly id: ReportId;
  readonly name: string;
  readonly read: boolean;
  readonly write: boolean;
  readonly input: boolean;
  readonly payloadLength?: number;
  readonly sensitive: boolean;
  readonly layout: 'implemented' | 'unverified';
}

export const reportDefinitions: readonly ReportDefinition[] = Object.freeze([
  Object.freeze({
    id: ReportId.PenData,
    name: 'PenData',
    read: false,
    write: false,
    input: true,
    payloadLength: 6,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.Status,
    name: 'Status',
    read: true,
    write: false,
    input: false,
    payloadLength: 4,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.Reset,
    name: 'Reset',
    read: false,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.HidInformation,
    name: 'HidInformation',
    read: true,
    write: false,
    input: false,
    payloadLength: 8,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.Information,
    name: 'Information',
    read: true,
    write: false,
    input: false,
    payloadLength: 16,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.Capability,
    name: 'Capability',
    read: true,
    write: false,
    input: false,
    payloadLength: 16,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.Uid,
    name: 'Uid',
    read: true,
    write: true,
    input: false,
    payloadLength: 4,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.Uid2,
    name: 'Uid2',
    read: true,
    write: false,
    input: false,
    payloadLength: 10,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.DefaultMode,
    name: 'DefaultMode',
    read: true,
    write: true,
    input: false,
    payloadLength: 2,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.ReportRate,
    name: 'ReportRate',
    read: true,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.RenderingMode,
    name: 'RenderingMode',
    read: true,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.Eserial,
    name: 'Eserial',
    read: true,
    write: false,
    input: false,
    payloadLength: 13,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.PenDataEncrypted,
    name: 'PenDataEncrypted',
    read: false,
    write: false,
    input: true,
    payloadLength: 16,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.HostPublicKey,
    name: 'HostPublicKey',
    read: true,
    write: true,
    input: false,
    payloadLength: 16,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.DevicePublicKey,
    name: 'DevicePublicKey',
    read: true,
    write: false,
    input: true,
    payloadLength: 16,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.StartCapture,
    name: 'StartCapture',
    read: false,
    write: true,
    input: false,
    payloadLength: 4,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.EndCapture,
    name: 'EndCapture',
    read: false,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.DHprime,
    name: 'DHprime',
    read: true,
    write: true,
    input: false,
    payloadLength: 16,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.DHbase,
    name: 'DHbase',
    read: true,
    write: true,
    input: false,
    payloadLength: 2,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.ClearScreen,
    name: 'ClearScreen',
    read: false,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.InkingMode,
    name: 'InkingMode',
    read: true,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.InkThreshold,
    name: 'InkThreshold',
    read: true,
    write: true,
    input: false,
    payloadLength: 4,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.ClearScreenArea,
    name: 'ClearScreenArea',
    read: false,
    write: true,
    input: false,
    payloadLength: 10,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.StartImageDataArea,
    name: 'StartImageDataArea',
    read: false,
    write: true,
    input: false,
    payloadLength: 10,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.StartImageData,
    name: 'StartImageData',
    read: false,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.ImageDataBlock,
    name: 'ImageDataBlock',
    read: false,
    write: true,
    input: false,
    payloadLength: 255,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.EndImageData,
    name: 'EndImageData',
    read: false,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.HandwritingThicknessColor,
    name: 'HandwritingThicknessColor',
    read: true,
    write: true,
    input: false,
    payloadLength: 3,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.BackgroundColor,
    name: 'BackgroundColor',
    read: true,
    write: true,
    input: false,
    payloadLength: 2,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.HandwritingDisplayArea,
    name: 'HandwritingDisplayArea',
    read: true,
    write: true,
    input: false,
    payloadLength: 8,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.BacklightBrightness,
    name: 'BacklightBrightness',
    read: true,
    write: true,
    input: false,
    payloadLength: 2,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.ScreenContrast,
    name: 'ScreenContrast',
    read: true,
    write: true,
    input: false,
    payloadLength: 2,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.HandwritingThicknessColor24,
    name: 'HandwritingThicknessColor24',
    read: true,
    write: true,
    input: false,
    payloadLength: 4,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.BackgroundColor24,
    name: 'BackgroundColor24',
    read: true,
    write: true,
    input: false,
    payloadLength: 3,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.BootScreen,
    name: 'BootScreen',
    read: true,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.PenDataOption,
    name: 'PenDataOption',
    read: false,
    write: false,
    input: true,
    payloadLength: 8,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.PenDataEncryptedOption,
    name: 'PenDataEncryptedOption',
    read: false,
    write: false,
    input: true,
    payloadLength: 20,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.PenDataOptionMode,
    name: 'PenDataOptionMode',
    read: true,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.PenDataTimeCountSequenceEncrypted,
    name: 'PenDataTimeCountSequenceEncrypted',
    read: false,
    write: false,
    input: true,
    payloadLength: 16,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.PenDataTimeCountSequence,
    name: 'PenDataTimeCountSequence',
    read: false,
    write: false,
    input: true,
    payloadLength: 10,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.EncryptionCommand,
    name: 'EncryptionCommand',
    read: true,
    write: true,
    input: false,
    payloadLength: 67,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.EncryptionStatus,
    name: 'EncryptionStatus',
    read: true,
    write: false,
    input: true,
    payloadLength: 16,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.GetReport,
    name: 'GetReport',
    read: false,
    write: true,
    input: false,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.SetResult,
    name: 'SetResult',
    read: false,
    write: false,
    input: true,
    payloadLength: 1,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.PinPadData,
    name: 'PinPadData',
    read: false,
    write: false,
    input: true,
    sensitive: true,
    layout: 'unverified' as const,
  }),
  Object.freeze({
    id: ReportId.PinPadDataEncrypted,
    name: 'PinPadDataEncrypted',
    read: false,
    write: false,
    input: true,
    sensitive: true,
    layout: 'unverified' as const,
  }),
  Object.freeze({
    id: ReportId.PinOperationMode,
    name: 'PinOperationMode',
    read: true,
    write: true,
    input: false,
    sensitive: false,
    layout: 'unverified' as const,
  }),
  Object.freeze({
    id: ReportId.OperationMode,
    name: 'OperationMode',
    read: true,
    write: true,
    input: false,
    payloadLength: 12,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.RomStartImageData,
    name: 'RomStartImageData',
    read: false,
    write: true,
    input: false,
    payloadLength: 6,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.RomImageOccupancy,
    name: 'RomImageOccupancy',
    read: true,
    write: true,
    input: false,
    sensitive: false,
    layout: 'unverified' as const,
  }),
  Object.freeze({
    id: ReportId.RomImageHash,
    name: 'RomImageHash',
    read: true,
    write: true,
    input: false,
    payloadLength: 19,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.RomImageDelete,
    name: 'RomImageDelete',
    read: false,
    write: true,
    input: false,
    payloadLength: 2,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.CurrentImageArea,
    name: 'CurrentImageArea',
    read: true,
    write: false,
    input: false,
    payloadLength: 8,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.EventData,
    name: 'EventData',
    read: false,
    write: false,
    input: true,
    payloadLength: 9,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.EventDataEncrypted,
    name: 'EventDataEncrypted',
    read: false,
    write: false,
    input: true,
    payloadLength: 16,
    sensitive: true,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.RomImageDisplay,
    name: 'RomImageDisplay',
    read: false,
    write: true,
    input: false,
    payloadLength: 2,
    sensitive: false,
    layout: 'implemented' as const,
  }),
  Object.freeze({
    id: ReportId.ReportSizeCollection,
    name: 'ReportSizeCollection',
    read: true,
    write: false,
    input: false,
    payloadLength: 511,
    sensitive: false,
    layout: 'implemented' as const,
  }),
]);

export function getReportDefinition(id: number): ReportDefinition | undefined {
  return reportDefinitions.find((report) => report.id === id);
}

export const StatusCode = {
  Ready: 0,
  Image: 1,
  Capture: 2,
  Calculation: 3,
  Boot: 4,
  RomBusy: 5,
  Reset: 255,
} as const;
export const EncodingMode = {
  Mono: 0,
  MonoZlib: 1,
  Rgb565: 2,
  Bgr24: 4,
  MonoBulk: 16,
  Rgb565Bulk: 18,
  Bgr24Bulk: 20,
} as const;
export const EncodingFlag = { Zlib: 1, Mono: 2, Rgb565: 4, Bgr24: 8 } as const;
export const PenDataOptionMode = { None: 0, Time: 1, Sequence: 2, TimeSequence: 3 } as const;
